server:
  port: 8084

spring:
  application:
    name: escola-backend
  datasource:
    url: jdbc:postgresql://localhost:5436/escola_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
